### ISSUE TITLE
Memory leak when premature end of stream with density codec

### ISSUE THREAD

**Issue by elliotwoods** [quixdb/squash#198] opened 2016-04-20 15:11 UTC
When:
* Using density codec
* Stream API
* **`squash_stream_finish` is not called**
* `squash_stream_destory` and then `squash_stream_unref(...)` are called

There is a memory leak.
An example of where this might happen is when a decompression stream fails (e.g. some packets are lost) in a network stream. Then the next frame comes in and the stream has to be refreshed to work on the next data instead. Since this can happen frequently over a long period of time, it causes a crash.

I tested with the other codecs which appear to properly support streaming, and didn't see this memory issue:
* lz4
* heatshrink

Screenshot of memory test:
![image](https://cloud.githubusercontent.com/assets/328294/14679594/919a4fcc-0755-11e6-9c2b-840e721e00a8.png)
(notice graph of memory usage is ascending)

**Comment by nemequ** [comment] 2016-04-20 21:42
Thanks for the report; I definitely want to know about this sort of issue.  It's hard to be certain it's the same issue without a test case (or at least a backtrace), but I think this is the same issue as https://github.com/centaurean/density/issues/53

Unfortunately I don't think there is anything we can do in Squash to work around this; the issue needs to be fixed in density.  I'm going to close this as a duplicate of centaurean/density#53, but feel free to reopen it if you think it's a separate issue.

**Closed by nemequ** 2016-04-20 21:42 UTC
Labels: bug, duplicate, plugins

**Comment by elliotwoods** [comment] 2016-04-21 04:21
thanks for pointing me in the right direction! (good to know it's a known issue)
yes i guessed it wasn't really going to be something that would be fixed in squash itself

also to check
1. what should i be calling after i finish using a stream? `squash_stream_destory`?  `squash_stream_unref`?
2. is this usage different if the stream is finished or not?
3. can i recycle a stream after using it (e.g. call `squash_stream_init`)?

also another question (very unrelated)
where can i learn the best way to use `SquashOptions` e.g. with LZ4?

**Comment by nemequ** [comment] 2016-04-21 04:59
> 1. what should i be calling after i finish using a stream? squash_stream_destory? squash_stream_unref?

`squash_object_unref`.  The `*_destroy` functions should only be used for inheritance; see http://quixdb.github.io/squash/api/c/group__SquashObject.html#gaa4dabc116f6e3b520084f1dfb56f71cd for a quick explanation of what is going on.

> 2. is this usage different if the stream is finished or not?

No.

> 3. can i recycle a stream after using it (e.g. call squash_stream_init)?

Not currently.  There is a (rather outdated) wip/reset branch to add the ability to reset streams, but it will use a new function, not `squash_stream_init`.  The `squash_*_init` functions are a lot like the `squash_*_destroy` functions in that they should only ever be called when implementing a subclass.

Note that very few codecs actually support resetting the stream (zlib and LZHAM are the only ones I can think of off the top of my head, but there may be others)…  usually the plugin will have to emulate the reset operation by destroying the old stream and creating a new one; all you would really save in that case is the cost in the Squash plugin code, which is pretty minimal.

> where can i learn the best way to use SquashOptions e.g. with LZ4?

Each plugin's documentation has a list of acceptable options; LZ4's is at http://quixdb.github.io/squash/api/c/md_plugins_lz4_lz4.html (if you're using git master instead of 0.7 you can use https://github.com/quixdb/squash/blob/wip/reset/plugins/lz4/lz4.md).

If you're asking about the API and not which options are supported, it's pretty straightforward.  You just create a `SquashOptions`, then pass that to the stream.  Basically;

```C
SquashOptions* options = squash_options_new (codec, "level", "7", NULL);
SquashStream* stream = squash_stream_new_codec_with_options (codec, SQUASH_STREAM_COMPRESS, options);
```

You can provide multiple options by adding additional argument pairs, or by calling one of the `squash_options_parse*` functions.

You can also shorten it using one of the convenience functions…

```C
SquashStream* stream = squash_stream_new_codec (codec, SQUASH_STREAM_COMPRESS, "level", "7", NULL);
```

Internally, this will just create a `SquashOptions` instance and pass it to `squash_stream_new_codec_with_options`.

If you choose to create a `SquashOptions` instance yourself, the only thing you really need to be careful of is that it returns a floating reference.  If you don't know what that means, https://developer.gnome.org/gobject/stable/gobject-The-Base-Object-Type.html#floating-ref is a decent introduction to the concept.
